(() => {
  const URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQmVbNM2gBp5BzWLEVmp4gXvXLX9B-Lv62vqXiTLfN1IJ26uhe8M9fbudwtJVP4WVCQVdW7qd_NnewY/pub?gid=1899560077&single=true&output=csv";
  const MAX = 1000000;
  let chart = null;
  const nomes = {"01":"Janeiro","02":"Fevereiro","03":"Março","04":"Abril","05":"Maio","06":"Junho","07":"Julho","08":"Agosto","09":"Setembro","10":"Outubro","11":"Novembro","12":"Dezembro"};
  const diasWebinar = [1,2,3,4];
  const nomesSemana = ["Domingo","Segunda","Terça","Quarta","Quinta","Sexta","Sábado"];
  const brl = v => Number(v || 0).toLocaleString("pt-BR", {style:"currency", currency:"BRL"});
  const norm = v => String(v || "").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
  const money = v => { const n = Number(String(v || "").replace(/[R$\s]/g, "").replace(/\./g, "").replace(",", ".")) || 0; return n > MAX ? 0 : n; };
  const set = (id, v) => { const el = document.getElementById(id); if (el) el.textContent = v; };
  function parseCSV(text){ const rows=[]; let row=[], field="", quoted=false; for(let i=0;i<text.length;i++){ const c=text[i], n=text[i+1]; if(c==='"'){ if(quoted&&n==='"'){field+='"';i++;} else quoted=!quoted; continue;} if(c===","&&!quoted){row.push(field.trim());field="";continue;} if((c==="\n"||c==="\r")&&!quoted){ if(c==="\r"&&n==="\n")i++; row.push(field.trim()); rows.push(row); row=[]; field=""; continue;} field+=c;} if(field||row.length){row.push(field.trim());rows.push(row);} return rows.filter(r=>r.some(c=>String(c).trim()!=="")); }
  function dataInfo(v){ const s=String(v||"").trim(); let m=s.match(/^(\d{2})\/(\d{2})$/); if(m)return{label:m[1]+"/"+m[2],mes:m[2],dia:Number(m[1]),ano:2026}; m=s.match(/^(\d{4})-(\d{2})-(\d{2})(?:\s+.*)?$/); if(m)return{label:m[3]+"/"+m[2],mes:m[2],dia:Number(m[3]),ano:Number(m[1])}; return null; }
  function base(matriz){ const ignorar=new Set(["total vendido/dia","total vendido/mes","total vendido/mês","meta","faltando","meta diaria","meta diária","falta para meta","total para meta"]); let headerIndex=-1,maxDates=0; matriz.forEach((linha,index)=>{ if(!linha.some(c=>norm(c)==="closer"))return; const qtd=linha.filter(c=>dataInfo(c)).length; if(qtd>maxDates){maxDates=qtd;headerIndex=index;} }); if(headerIndex===-1)return{meses:{}}; const header=matriz[headerIndex]; const closerCol=header.findIndex(c=>norm(c)==="closer"); const cols=header.map((cell,index)=>({...dataInfo(cell),index})).filter(x=>x.label).sort((a,b)=>a.mes===b.mes?a.dia-b.dia:Number(a.mes)-Number(b.mes)); const vendedores=[]; for(let i=headerIndex+1;i<matriz.length;i++){ const linha=matriz[i]; const nome=String(linha[closerCol]||"").trim(); const n=norm(nome); if(!nome)continue; if(ignorar.has(n)||n.includes("total")||n.includes("meta")||n.includes("falta"))break; const vendas={}; cols.forEach(col=>vendas[col.label]=money(linha[col.index])); vendedores.push({nome,vendas}); } const meses={}; cols.forEach(col=>{ if(!meses[col.mes])meses[col.mes]={mes:col.mes,label:(nomes[col.mes]||col.mes)+"/"+col.ano,dias:[],totalDia:{},webinar:{}}; if(!meses[col.mes].dias.includes(col.label))meses[col.mes].dias.push(col.label); }); Object.values(meses).forEach(m=>{ m.dias.sort((a,b)=>Number(a.split("/")[0])-Number(b.split("/")[0])); m.dias.forEach(day=>m.totalDia[day]=vendedores.reduce((s,v)=>s+(v.vendas[day]||0),0)); m.total=m.dias.reduce((s,d)=>s+m.totalDia[d],0); diasWebinar.forEach(w=>m.webinar[w]={nome:nomesSemana[w],dias:[],total:0,media:0}); m.dias.forEach(day=>{ const parts=day.split("/").map(Number); const date=new Date(2026,parts[1]-1,parts[0]); const w=date.getDay(); if(diasWebinar.includes(w)){ m.webinar[w].dias.push(day); m.webinar[w].total+=m.totalDia[day]||0; }}); diasWebinar.forEach(w=>{ const qtd=m.webinar[w].dias.length||1; m.webinar[w].media=m.webinar[w].total/qtd; }); m.webinarTotal=diasWebinar.reduce((s,w)=>s+m.webinar[w].total,0); m.webinarDias=diasWebinar.reduce((s,w)=>s+m.webinar[w].dias.length,0); m.webinarMedia=m.webinarTotal/Math.max(m.webinarDias,1); }); return{meses}; }
  function fill(baseData){ const a=document.getElementById("webinarMonthA"), b=document.getElementById("webinarMonthB"); if(!a||!b)return; const meses=Object.values(baseData.meses).sort((x,y)=>Number(x.mes)-Number(y.mes)); const cur=String(new Date().getMonth()+1).padStart(2,"0"); const prev=String(new Date().getMonth()).padStart(2,"0"); const va=a.value||localStorage.getItem("webinarMonthA")||prev; const vb=b.value||localStorage.getItem("webinarMonthB")||cur; a.replaceChildren(); b.replaceChildren(); meses.forEach(m=>{ const oa=document.createElement("option"); oa.value=m.mes; oa.textContent=m.label; const ob=document.createElement("option"); ob.value=m.mes; ob.textContent=m.label; a.append(oa); b.append(ob); }); a.value=meses.some(m=>m.mes===va)?va:meses[0]?.mes; b.value=meses.some(m=>m.mes===vb)?vb:meses[meses.length-1]?.mes; a.onchange=()=>{localStorage.setItem("webinarMonthA",a.value); render(baseData);}; b.onchange=()=>{localStorage.setItem("webinarMonthB",b.value); render(baseData);}; }
  function render(baseData){ const a=document.getElementById("webinarMonthA"), b=document.getElementById("webinarMonthB"); if(!a||!b)return; const ma=baseData.meses[a.value], mb=baseData.meses[b.value]; if(!ma||!mb)return; const diff=mb.webinarTotal-ma.webinarTotal; const pct=ma.webinarTotal>0?diff/ma.webinarTotal*100:0; set("webinarTotalA",brl(ma.webinarTotal)); set("webinarTotalB",brl(mb.webinarTotal)); set("webinarDelta",(diff>=0?"+":"-")+brl(Math.abs(diff))); set("webinarPct",(pct>=0?"+":"")+pct.toFixed(2)+"%"); set("webinarAvg",brl(mb.webinarMedia)); set("webinarDays",mb.webinarDias+" dias"); const cls=diff>=0?"delta-up":"delta-down"; const d=document.getElementById("webinarDelta"), p=document.getElementById("webinarPct"); if(d)d.className=cls; if(p)p.className=cls; const legend=document.getElementById("webinarLegend"); if(legend)legend.textContent="Comparando apenas segundas, terças, quartas e quintas entre "+ma.label+" e "+mb.label+"."; renderDias(ma,mb); renderChart(ma,mb); }
  function renderDias(ma,mb){ const box=document.getElementById("webinarDaysGrid"); if(!box)return; box.replaceChildren(); diasWebinar.forEach(w=>{ const diff=mb.webinar[w].total-ma.webinar[w].total; const pct=ma.webinar[w].total>0?diff/ma.webinar[w].total*100:0; const card=document.createElement("div"); card.className="webinar-day-card"; const span=document.createElement("span"); span.textContent=mb.webinar[w].nome; const strong=document.createElement("strong"); strong.textContent=brl(mb.webinar[w].total); const small=document.createElement("small"); small.textContent=(diff>=0?"+":"-")+brl(Math.abs(diff))+" | "+(pct>=0?"+":"")+pct.toFixed(1)+"% vs mês A"; small.className=diff>=0?"delta-up":"delta-down"; card.append(span,strong,small); box.append(card); }); }
  function renderChart(ma,mb){ const canvas=document.getElementById("webinarChart"); if(!canvas||typeof Chart==="undefined")return; const existing=Chart.getChart?Chart.getChart(canvas):null; if(existing)existing.destroy(); if(chart)chart.destroy(); chart=new Chart(canvas,{type:"bar",data:{labels:diasWebinar.map(w=>nomesSemana[w]),datasets:[{label:ma.label,data:diasWebinar.map(w=>ma.webinar[w].total),backgroundColor:"rgba(99,102,241,.45)",borderColor:"#6366f1",borderWidth:2,borderRadius:12},{label:mb.label,data:diasWebinar.map(w=>mb.webinar[w].total),backgroundColor:"rgba(6,182,212,.55)",borderColor:"#06b6d4",borderWidth:2,borderRadius:12}]},options:{responsive:true,maintainAspectRatio:false,plugins:{tooltip:{callbacks:{label:ctx=>ctx.dataset.label+": "+brl(ctx.raw)}}},scales:{y:{beginAtZero:true,ticks:{callback:brl}}}}}); }
  async function init(){ try{ const r=await fetch(URL+"&webinar="+Date.now(),{cache:"no-store"}); if(!r.ok)throw new Error(r.status); const b=base(parseCSV(await r.text())); fill(b); render(b);}catch(e){console.error("Erro no comparativo de webinar:",e);} }
  setTimeout(init,1200); setInterval(init,300000);
})();
